### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by mikemorris** [fightforthefuture/2017Pledge#1]
# Questions:

### AWS
- [x] I need AWS credentials to generate an encrypted [`secret_access_key`](https://github.com/fightforthefuture/2017Pledge/blob/15b85fbefa6fdd292bf4736a8275f8c319460d4f/.travis.yml#L27-L28) if we want this repo to deploy `assets` directory to S3.

(i'm looking for this)

### Heroku
- [ ] What application is deployed at [https://mothership-js.herokuapp.com](https://github.com/fightforthefuture/2017Pledge/blob/15b85fbefa6fdd292bf4736a8275f8c319460d4f/_config.build.yml#L5) and does it have a corresponding GitHub repo?
- [ ] Does the Heroku app configuration in this repo need to be deployed anywhere or is this legacy code that can be removed?
  - `Procfile`
  - `app.json`

### Action Network
- [ ] Do we need to set the [`petition_id`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L1) for this form? [It looks like this wasn't set for the `rockagainstthetpp` site?](https://github.com/fightforthefuture/rockagainstthetpp/blob/production/site/_layouts/default.html#L47-L58)

(my understanding is yes.)

- [ ] What should the value of [`data-mothership-tag`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L1) be?

- [ ] Does the [`authenticity_token`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L15) need to be updated?
- [ ] What values should be used for [`subscription[sub_group_id]`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L17), [`subscription[source]`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L19) and [`signature[tag_list]`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/_includes/form.html#L20)? I'm assuming these are configured in the Action Network petition, but I don't see anywhere I can view or edit these values (maybe I need admin access?)
- [ ] Do we need to clean up the thanks/share modal that pops up after submitting the form?

(yes we need to, we need to give you language or you could wing it)

### Google Analytics
- [ ] Is [`UA-26576645-30`](https://github.com/fightforthefuture/2017Pledge/blob/15b85fbefa6fdd292bf4736a8275f8c319460d4f/_config.yml#L23) the correct code for this campaign?
- [ ] Update [`google-site-verification`](https://github.com/fightforthefuture/2017Pledge/blob/d0ad2aec00c868ba4aff298a7b7ba18c5d9b4567/site/googlea1fbcebd7efd8445.html)?

### Free Progress
- [ ] Is the `.env.example`/`.env` configuration currently in use? Only necessary for local dev?
- [ ] Where can I get a `FP_DOMAIN_SECURITY_TOKEN` to add to `.travis.yml`?
- [ ] [Does this need to be enabled for this site or should it be removed?](https://github.com/fightforthefuture/2017Pledge/blob/d300f39211654744f1281c9d53fe99359a2198eb/site/_includes/scripts.html#L12)

### `CNAME`
- [ ] What will the domain name for this site be? The `CNAME` file in this repo will need to be updated and [the DNS records will need to be updated to point to GitHub Pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).

(we also need to give you social media sharing text)

# TODO:
- [ ] [Install EditorConfig vim plugin](https://github.com/editorconfig/editorconfig-vim)

@rubbingalcoholic @katro16
